baseURL = "https://ammiranda.com"
languageCode = "en-us"
title = "alexmiranda"

theme = "hugo-coder"

defaultContentLanguage = "en"

[pagination]
	pagerSize = 20

[markup]
	[markup.highlight]
		noClasses = false
		style = "github-dark"

[markup.goldmark]
	[markup.goldmark.renderer]
		unsafe = true

[params]
	author = "Alex Miranda"
	description = "Alex Miranda's personal website"
	keywords = "blog,developer,personal"
	info = "Full Stack Software Engineer"
	avatarURL = "images/avatar_min.jpg"
	
	dateFormat = "January 2, 2006"
	since = 2020

	colorScheme = "auto"

	hideColorSchemeToggle = true

	maxSeeAlsoItems = 5

	enableTwemoji = false

	customCSS = []

	customSCSS = []

	customJS = []

[params.csp]
	connectsrc = ["'self'", "https://www.google-analytics.com"]
	childsrc = ["'self'"]
	fontsrc=["'self'",
		"https://fonts.gstatic.com",
		"https://cdn.jsdelivr.net/"]
	formaction = ["'self'"]
	framesrc = ["'self'"]
	imgsrc = ["'self'"]
	objectsrc = ["'none'"]
	stylesrc = ["'self'",
		"https://fonts.googleapis.com/",
		"https://cdn.jsdelivr.net/"]
	scriptsrc = ["'self'",
		"https://www.google-analytics.com"]
	prefetchsrc = ["'self'"]

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"
	author = "authors"

[[menu.main]]
	name = "About"
	weight = 1
	url = "about"
[[menu.main]]
	name = "Posts"
	weight = 2
	url = "posts"
[[menu.main]]
	name = "Contact me"
	weight = 3
	url = "contact"
[[menu.main]]
	name = "Resume"
	weight = 4
	url = "resume.pdf"
[[menu.main]]
	name = "PGP Key"
	weight = 5
	url = "pgp.txt"

[[params.social]]
	name = "Github"
	icon = "fab fa-github fa-2x"
	weight = 1
	url = "https://github.com/ammiranda/"
	target="_blank"
[[params.social]]
	name = "Docker"
	icon = "fab fa-docker fa-2x"
	weight = 2
	url = "https://hub.docker.com/u/amiranda"
	target = "_blank"
[[params.social]]
	name = "NPM"
	icon = "fab fa-npm fa-2x"
	weight = 3
	url = "https://www.npmjs.com/~alexmiranda"
	target = "_blank"
[[params.social]]
	name = "Twitter"
	icon = "fab fa-twitter fa-2x"
	weight = 4
	url = "https://twitter.com/amiranda222"
	target="_blank"
[[params.social]]
	name = "LinkedIn"
	icon = "fab fa-linkedin fa-2x"
	weight = 5
	url = "https://www.linkedin.com/in/alexmmiranda"
	target="_blank"
[[params.social]]
	name = "Keybase"
	icon = "fab fa-keybase fa-2x"
	weight = 6
	url = "https://keybase.io/amiranda"
	target = "_blank"
[[params.social]]
	name = "Email"
	icon = "fa fa-envelope fa-2x"
	weight = 6
	url = "mailto:alexandermichaelmiranda@gmail.com"
[[params.social]]
	name = "RSS"
	icon = "fa fa-rss fa-2x"
	weight = 7
	url = "https://ammiranda.com/index.xml"
	rel = "alternate"
	type = "application/rss+xml"
	target="_blank"