baseURL = "https://ammiranda.com/"
languageCode = "en-us"
title = "alexmiranda"

theme = "hugo-coder"

defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
	author = "Alex Miranda"
	description = "Alex Miranda's personal website"
	keywords = "blog,developer,personal"
	info = "Full Stack Web Engineer"
	
	dateFormat = "January 2, 2006"
	since = 2020

	colorScheme = "auto"

	hideColorSchemeToggle = false

	maxSeeAlsoItems = 5

	enableTwemoji = false

	customCSS = []

	customSCSS = []

	customJS = []

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"
	author = "authors"

[[params.social]]
	name = "Github"
	icon = "fa fa-github"
	weight = 1
	url = "https://github.com/ammiranda/"
[[params.social]]
	name = "Twitter"
	icon = "fa fa-twitter"
	weight = 3
	url = "https://twitter.com/amiranda222"
[[params.social]]
	name = "LinkedIn"
	icon = "fa fa-linkedin"
	weight = 4
	url = "https://www.linkedin.com/in/alexmmiranda"
[[params.social]]
	name = "RSS"
	icon = "fa fa-rss"
	weight = 6
	url = "https://ammiranda.com/index.xml"
	rel = "alternate"
	type = "application/rss+xml"

[languages]
	[languages.en]
		languageName = "English"

	[languages.en.menu]
		[[languages.en.menu.main]]
		name = "About"
		weight = 1
		url = "/about/"

		[[languages.en.menu.main]]
		name = "Blog"
		weight = 2
		url = "/posts/"

		[[languages.en.menu.main]]
		name = "Contact me"
		weight = 5
		url = "/contact/"
