baseURL = "https://ammiranda.com"
languageCode = "en-us"
title = "alexmiranda"

theme = "hugo-coder"

defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

googleAnalytics = "UA-162357221-1"

[params]
	author = "Alex Miranda"
	description = "Alex Miranda's personal website"
	keywords = "blog,developer,personal"
	info = "Full Stack Software Engineer"
	avatarURL = "images/avatar.jpg"
	
	dateFormat = "January 2, 2006"
	since = 2020

	colorScheme = "auto"

	hideColorSchemeToggle = false

	maxSeeAlsoItems = 5

	enableTwemoji = false

	customCSS = ["css/all.css"]

	customSCSS = []

	customJS = []

[params.csp]
	childsrc = ["'self'"]
	fontsrc=["'self'",
		"https://fonts.gstatic.com",
		"https://cdn.jsdelivr.net/"]
	formaction = ["'self'"]
	framesrc = ["'self'"]
	imgsrc = ["'self'"]
	objectsrc = ["'none'"]
	stylesrc = ["'self'",
		"'unsafe-inline'",
		"https://fonts.googleapis.com/",
		"https://cdn.jsdelivr.net/"]
	scriptsrc = ["'self'",
		"'unsafe-inline'",
		"https://www.google-analytics.com"]
	prefetchsrc = ["'self'"]

[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"
	author = "authors"

[[menu.main]]
	name = "About"
	weight = 1
	url = "about"
# [[menu.main]]
#	name = "Blog"
#	weight = 2
#	url = "posts"
[[menu.main]]
	name = "Contact me"
	weight = 5
	url = "contact"

[[params.social]]
	name = "Github"
	icon = "fab fa-github"
	weight = 1
	url = "https://github.com/ammiranda/"
	target="_blank"
[[params.social]]
	name = "Docker"
	icon = "fab fa-docker"
	weight = 2
	url = "https://hub.docker.com/u/amiranda"
	target = "_blank"
[[params.social]]
	name = "NPM"
	icon = "fab fa-npm"
	weight = 3
	url = "https://www.npmjs.com/~alexmiranda"
	target = "_blank"
[[params.social]]
	name = "Twitter"
	icon = "fab fa-twitter"
	weight = 4
	url = "https://twitter.com/amiranda222"
	target="_blank"
[[params.social]]
	name = "LinkedIn"
	icon = "fab fa-linkedin"
	weight = 5
	url = "https://www.linkedin.com/in/alexmmiranda"
	target="_blank"
[[params.social]]
	name = "Email"
	icon = "fa fa-envelope"
	weight = 6
	url = "mailto:alexandermichaelmiranda@gmail.com"
[[params.social]]
	name = "RSS"
	icon = "fa fa-rss"
	weight = 7
	url = "https://ammiranda.com/index.xml"
	rel = "alternate"
	type = "application/rss+xml"
	target="_blank"