name: build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Git submodule init
        run: git submodule init
      - name: Git submodule update
        run: git submodule update
      - name: Build Hugo
        uses: lowply/build-hugo@v0.148.0
