name: build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Clone theme for build
        run: git clone https://github.com/luizdepra/hugo-coder.git themes/hugo-coder
      - name: Build Hugo
        uses: lowply/build-hugo@v0.79.0
