name: deploy

on:
  push:
    branches:
      - master

env:
  TARGET_ADDRESS: ${{ secrets.TARGET_ADDRESS }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2
  CLOUDFRONT_DISTRO_ID: ${{ secrets.CLOUDFRONT_DISTRO_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Gatsby build
        run: npm run build --if-present
      - run: npm test
      - run: aws configure --profile default <<-EOF > /dev/null 2>&1 $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_REGION json
      - name: Deploy and invalidate cache
        run: npm run deploy && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRO_ID --paths \"/*\"
