name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Git submodule init
        run: git submodule init
      - name: Git submodule update
        run: git submodule update
      - name: Build Hugo
        uses: lowply/build-hugo@v0.79.0
      - name: Deploy to S3 and Invalidate Cloudfront distro
        uses: ammiranda/s3-sync-cloudfront-invalidate-docker-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'public'
          AWS_CLOUDFRONT_PATH: '/*'
          AWS_CLOUDFRONT_DISTRO_ID: ${{ secrets.CLOUDFRONT_DISTRO_ID }}
